services:
  postgres:
    image: postgres:15-alpine
    container_name: auth_db
    environment:
      POSTGRES_USER: seyha
      POSTGRES_PASSWORD: seyha123
      POSTGRES_DB: auth_db
    ports:
      - "5444:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  auth_postgres_data: